= Projeto URA - Versão 4
:listing-caption: Listing
:toc: left
:icons: font
:source-highlighter: highlightjs

== Introdução

* Este arquivo tem como objetivo relatar as modificações, bem como o processo de montagem da **Versão 4** do projeto _https://github.com/lar-ect/URA[Um Robô por Aluno (URA)^]_, idealizado pelo professor _https://github.com/orivaldosantana[Orivaldo Santana^]_, e realizado pelos alunos do _https://github.com/lar-ect[Laboratório de Robótica (LAR)^]_ da _http://www.ect.ufrn.br/[Escola de Ciências e Tecnologia (ECT)^]_.

* Nessa versão, os robôs foram construídos com o intuito de realizar experimentos físicos de **_Movimento Retilínio Uniforme_** e **_Uniformimente Variado (MRU e MRUV)_** juntamente com a mestranda em física **_Natana Rodrigues_**, que aplicou esses experimentos junto a alunos de ensino médio.

== Componentes
== Montagem
== Etapas da programação
* A realização do projeto contou com a criação de uma classe em `C++` que gerencia ambos os motores do carro com auxílio da biblioteca https://www.arduino.cc/en/Reference/Servo[Servo^], e métodos que ajudam o controle do robô por meio da interface bluetooth adotada. A classe com suas alterações finais, bem como a implementação no _arduino_, estão disponíveis https://github.com/lar-ect/URA/tree/master/versao%204/codigos/arduino/devs/Fisica/TempoMovimenoLinear[aqui^].

* Durante a implementação, foram realizados testes como _proof of concept_ para comprovar se os motores e métodos adotados eram suficientemente viáveis para a realização de trajetos em **MRU** e **MRUV**, para tanto, foram observados as seguintes variáveis:

=== Potência dos motores
* Primeiramente, a ideia adotada para a escrever uma potência constante no mortor _Servo_ foi utilizar o método `writeMicroseconds(int)` referenciado https://www.arduino.cc/en/Reference/ServoWriteMicroseconds[aqui^]. Com este método mapeamos os valores dos motores de um carrinho para:

[%autowidth]
.Valores dos motores em uS de min - máx
|===
|Servo |Parado |Horário |Anti-horário

|Motor esquerdo
|1450
|1449 - 0
|1451 - 1800

|Motor direito
|1450
|1451 - 1800
|1449 - 0

|===

* Entretanto os valores encontrados não eram constantes para todos os motores, além de o intervalo entre os valorem mínimos e máximos não se comportaram de maneira linear em relação ao _RPM_ resultante. Portanto o uso da função `writeMicroseconds(int)` funcionou somente na implementação da função seguinte, que aplica uma velocidade constante ao robô.

[source, c++]
._ServoMotor.cpp_
----
void ServoMotor::frente(){
    //mDireito e mEsquerdo sao variaveis do tipo Servo
    mDireito.writeMicroseconds(paradoDireito+intensidade); 
    mEsquerdo.writeMicroseconds(paradoEsquerdo-intensidade); 
} 
----

=== Rotação dos motores
* Com o código seguinte, testou-se como os motores se comportavam em relação a direção de rotação e a proporção entre o valor escrito em _Pulse Width Modulation (PWM)_.

[source, c++]
._teste_rotacao.ino_
----
#include <Servo.h>

Servo mDir, mEsq;  // servo motores
int val = 0; // valor de teste
...
void loop() {
  mDir.write(val);
  mEsq.write(val);
  delay(150);
  Serial.println(val); // mostra o valor que foi escrito nos motores
  if(val<180) val++;
  else val = 0; // faz com que o valor escrito seja circular 0-180
}
----

== Motivação
